In [1]:
import numpy

In [3]:
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
# Reshape to 3x9 since we have 27 elements
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [5]:
import cv2

In [7]:
im_gray = cv2.imread("smallgray.png", 0)
im_gray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [8]:
# Create image from array using numpy

cv2.imwrite("new_image.png", im_gray)

True

In [9]:
# extract specific array items , 3-4 colums 2-3 rows

im_gray[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [10]:
# iterate values one by one

for i in im_gray.flat:
  print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [12]:
# Horizontally stack arrays
# must put it inside tuple , so we cna stack

stacked = numpy.hstack((im_gray, im_gray))
stacked

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
# Vertically stack arrays
v_stacked = numpy.vstack((im_gray, im_gray))
v_stacked

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [16]:
# Splitting array horizontally
splitted = numpy.vsplit(v_stacked, 3)
splitted

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]